In [1]:
from __future__ import absolute_import, division, print_function, unicode_literals

import tensorflow as tf
import matplotlib.pyplot as plt
import lib.cell as cell
import lib.spec as spec
from lib.model import NModel
import numpy as np



(train_images, train_labels), (test_images, test_labels) = tf.keras.datasets.cifar10.load_data()

# Normalize pixel values to be between 0 and 1
train_images, test_images = train_images / 255.0, test_images / 255.0

In [7]:

cf = spec.Spec.get_configuration_space().sample_configuration()
s = spec.Spec(cf)
while s.valid_spec == False:
    cf = spec.Spec.get_configuration_space().sample_configuration()
    s = spec.Spec(cf)

print(s.matrix)
print(s.ops)

[[0 1 1 0]
 [0 0 0 1]
 [0 0 0 1]
 [0 0 0 0]]
['input', 'conv3x3-bn-relu', 'conv1x1-bn-relu', 'output']


In [8]:
i = tf.keras.Input(shape=(32, 32, 3))
o = NModel(spec=s, inputs=i).build()
model = tf.keras.Model(i, o, name="sample_model")
model.summary()

___________________
concatenate_28 (Concatenate)    (None, 32, 32, 128)  0           re_lu_113[0][0]                  
                                                                 re_lu_115[0][0]                  
__________________________________________________________________________________________________
conv2d_120 (Conv2D)             (None, 32, 32, 64)   8192        concatenate_28[0][0]             
__________________________________________________________________________________________________
conv2d_122 (Conv2D)             (None, 32, 32, 64)   8192        concatenate_28[0][0]             
__________________________________________________________________________________________________
batch_normalization_116 (BatchN (None, 32, 32, 64)   256         conv2d_120[0][0]                 
__________________________________________________________________________________________________
batch_normalization_118 (BatchN (None, 32, 32, 64)   256         conv2d_122[0][0]        

In [9]:
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])
history = model.fit(train_images, train_labels, epochs=5, validation_data=(test_images, test_labels))

Train on 50000 samples, validate on 10000 samples
Epoch 1/5
50000/50000 [==============================] - 52s 1ms/sample - loss: 1.2299 - accuracy: 0.5563 - val_loss: 4.4468 - val_accuracy: 0.3752
Epoch 2/5
50000/50000 [==============================] - 48s 968us/sample - loss: 0.7805 - accuracy: 0.7275 - val_loss: 2.2318 - val_accuracy: 0.4841
Epoch 3/5
50000/50000 [==============================] - 48s 960us/sample - loss: 0.6075 - accuracy: 0.7895 - val_loss: 1.0121 - val_accuracy: 0.7103
Epoch 4/5
50000/50000 [==============================] - 48s 966us/sample - loss: 0.5010 - accuracy: 0.8283 - val_loss: 1.3125 - val_accuracy: 0.6284
Epoch 5/5
50000/50000 [==============================] - 48s 964us/sample - loss: 0.4220 - accuracy: 0.8546 - val_loss: 1.2608 - val_accuracy: 0.6437
